### ISSUE TITLE
Error when inspecting a template using the flag  --aql-path 

### ISSUE THREAD

**Issue by abebehailu** [crs4/flatehr#48]
FlatEHR Version: 1.1.0

Running the following command "flatehr inspect --aql-path --inputs webtemplate.json" on one of our templates produces the following error message.

`
Traceback (most recent call last):
  File "/home/abbe/.local/bin/flatehr", line 8, in <module>
    sys.exit(main())
  File "/home/abbe/.local/lib/python3.8/site-packages/flatehr/cli/entrypoint.py", line 10, in main
    defopt.run(
  File "/home/abbe/.local/lib/python3.8/site-packages/defopt.py", line 356, in run
    return call()
  File "/home/abbe/.local/lib/python3.8/site-packages/flatehr/cli/inspect_template.py", line 24, in main
    _aql_path = ", " + node.aql_path if aql_path else ""
TypeError: can only concatenate str (not "NoneType") to str
`

The error message does not state where the issue is in the template file. Would be nice to have some information regarding the node in the error output.

**Comment by ErikSundvall** [comment]
It was (I believe) a "web template"-exported/converted version of https://github.com/modellbibliotek/CKM-mirror/blob/lekstuga/local/Lab_result_report_stockholm.v2.t.json that may have had the export error of repeated siblings with same node ID as described in https://discourse.openehr.org/t/specialized-node-ids-are-lost-on-opt-export/3036

I do not know if that could have caused the error or something else. Anyway error messages including info about the position in web the template of causing problems would be helpful.

**Comment by mdrio** [comment]
I created a PR for this issue, #50. It raises an exception with more information related to the problematic node. Not sure how to reproduce your issue, is it possibile to attach the web template you used @abebehailu?

**Comment by mdrio** [comment]
Not sure if aqlPath is a "MUST HAVE" specification, anyway since it is not a required field for flatehr to work properly, I think the exception can be managed via some warning.
